changelog:
  exclude:
    labels:
      - ignore-for-release
      - internal
      - skip-changelog

  categories:
    - title: "🚨 Breaking Changes"
      labels:
        - breaking-change
        - semver-major

    - title: "🚀 Features"
      labels:
        - enhancement
        - feature
        - semver-minor

    - title: "🐛 Bug Fixes"
      labels:
        - bug
        - fix

    - title: "🔧 Maintenance"
      labels:
        - maintenance
        - chore

    - title: "📚 Documentation"
      labels:
        - documentation
        - docs

    - title: "📦 Other Changes"
      labels:
        - "*"