name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    uses: divyasingh0/az_tf_workflow/.github/workflows/release-please.yml@v1.0.0
    with:
      config_file: .release-please-config.json
      manifest_file: .release-please-manifest.json
      target_branch: main
    secrets: inherit
