name: Application Deployment

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

      application_name:
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:

  deploy:

    runs-on: ubuntu-latest

    environment: ${{ inputs.environment }}

    steps:

      - uses: actions/checkout@v4

      - name: Build
        run: echo "Build Application"

      - name: Test
        run: echo "Run Unit Tests"

      - name: Security Scan
        run: echo "Run Security Scans"

      - name: Deploy
        run: |
          echo "Deploying ${{ inputs.application_name }}"
