name: Terraform PR Workflow

on:
  workflow_call:
    inputs:
      environment:
        description: "Terraform environment (dev, test, prod , sandbox)"
        required: true
        type: string

      working_directory:
        description: "Terraform working directory"
        required: false
        default: .
        type: string

permissions: write-all

env:
  WORKING_DIR: ./
  TERRAFORM_VERSION: 1.8.5
  TF_IN_AUTOMATION: true
  TF_INPUT: false

jobs:

  validate:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read Terraform Version
        id: tf_version
        run: echo "version=$(cat .terraform-version)" >> $GITHUB_OUTPUT

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ steps.tf_version.outputs.version }}

      - name: Validate Environment Files
        run: |
          test -f environment/${{ inputs.environment }}/backend.tfvars
          test -f environment/${{ inputs.environment }}/${{ inputs.environment }}.tfvars

      - name: Terraform Init
        run: |
          git config --global url."https://x-access-token:${{ secrets.GH_PAT }}@github.com/".insteadOf "https://github.com/"

          terraform init -backend=false -input=false

      - name: Terraform FMT
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate

      # - name: Setup TFLint
      #   uses: terraform-linters/setup-tflint@v4

      # - name: TFLint Init
      #   run: tflint --init

      # - name: Run TFLint
      #   run: tflint --recursive

      # - name: Checkov Security Scan
      #   uses: bridgecrewio/checkov-action@v12
      #   with:
      #     directory: .
      #     framework: terraform
      #     soft_fail: false


  plan:

    needs: validate

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Read Terraform Version
        id: tf_version
        run: echo "version=$(cat .terraform-version)" >> $GITHUB_OUTPUT

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ steps.tf_version.outputs.version }}

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform Init
        run: |
          git config --global url."https://x-access-token:${{ secrets.GH_PAT }}@github.com/".insteadOf "https://github.com/"

          terraform init -backend=false -input=false

      - name: Terraform Plan
        run: |
          terraform plan \
            -var-file=environment/${{ inputs.environment }}/${{ inputs.environment }}.tfvars \
            -out=tfplan

      - name: Generate Plan Output
        run: terraform show -no-color tfplan > tfplan.txt

      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan-${{ github.sha }}
          path: |
            tfplan
            tfplan.txt
 